"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const emergency_api_controller_1 = require("../../controllers/emergency-api.controller");
const auth_middleware_1 = require("../../middlewares/auth.middleware");
const express_1 = require("express");
const adminRouter = (0, express_1.Router)();
adminRouter.get("/emergencies", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.getAdminEmergencyRequests);
adminRouter.get("/emergencies/active", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.getActiveEmergencies);
adminRouter.get("/emergencies/:id/track", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.trackEmergencyRequest);
adminRouter.post("/emergencies/:id/approve", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.approveEmergencyRequest);
adminRouter.post("/emergencies/:id/reject", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.rejectEmergencyRequest);
adminRouter.post("/emergencies/:id/assign", (0, auth_middleware_1.validateRoleAuth)(["admin"]), emergency_api_controller_1.assignResponder);
exports.default = adminRouter;
