"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const auth_api_controller_1 = require("../../controllers/auth-api.controller");
const rate_limit_middleware_1 = require("../../middlewares/rate-limit.middleware");
const auth_middleware_1 = require("../../middlewares/auth.middleware");
const express_1 = require("express");
const authRouter = (0, express_1.Router)();
authRouter.post("/register", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.register);
authRouter.post("/send-registration-otp", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 5, windowMs: 60_000 }), auth_api_controller_1.sendRegistrationOtp);
authRouter.post("/verify-registration", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.verifyRegistration);
authRouter.post("/login", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.login);
authRouter.patch("/me/location", (0, auth_middleware_1.validateRoleAuth)(["user", "admin"]), auth_api_controller_1.updateMyLocation);
authRouter.patch("/me/profile", (0, auth_middleware_1.validateRoleAuth)(["user", "admin"]), auth_api_controller_1.updateMyProfile);
authRouter.post("/forgot-password", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 5, windowMs: 60_000 }), auth_api_controller_1.forgotPassword);
authRouter.post("/reset-password", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.resetPassword);
exports.default = authRouter;
