"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const auth_api_controller_1 = require("../../controllers/auth-api.controller");
const rate_limit_middleware_1 = require("../../middlewares/rate-limit.middleware");
const express_1 = require("express");
const authRouter = (0, express_1.Router)();
authRouter.post("/register", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.register);
authRouter.post("/login", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.login);
authRouter.post("/forgot-password", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 5, windowMs: 60_000 }), auth_api_controller_1.forgotPassword);
authRouter.post("/reset-password", (0, rate_limit_middleware_1.createRateLimiter)({ limit: 10, windowMs: 60_000 }), auth_api_controller_1.resetPassword);
exports.default = authRouter;
